INSERT INTO nikkes (nikke_id, rarity, name, manufacturer, element, weapon, role, squad, burst) VALUES
(1, 3, '2B', 'Abnormal', 'Fire', 'AR', 'Defender', 'YoRHa', 3),
(2, 3, 'A2', 'Abnormal', 'Fire', 'RL', 'Attacker', 'YoRHa', 3),
(3, 3, 'Ada', 'Abnormal', 'Electric', 'RL', 'Attacker', 'B.S.T', 3),
(4, 3, 'Ade', 'Tetra', 'Wind', 'AR', 'Supporter', 'Maid For You', 2),
(5, 3, 'Ade: Agent Bunny', 'Tetra', 'Iron', 'SR', 'Supporter', 'Maid For You', 2),
(6, 3, 'Admi', 'Missilis', 'Wind', 'SR', 'Supporter', 'Triangle', 2),
(7, 3, 'Alice', 'Tetra', 'Fire', 'SR', 'Attacker', 'Unlimited', 3),
(8, 3, 'Alice: Wonderland Bunny', 'Tetra', 'Water', 'SMG', 'Supporter', 'Unlimited', 1),
(9, 3, 'Anchor: Innocent Maid', 'Elysion', 'Water', 'RL', 'Supporter', 'Aegis', 2),
(10, 3, 'Anis: Sparkling Summer', 'Tetra', 'Electric', 'SG', 'Supporter', 'Counters', 3),
(11, 3, 'Anne: Miracle Fairy', 'Missilis', 'Wind', 'RL', 'Supporter', 'Recall & Release', 2),
(12, 3, 'Arcana', 'Elysion', 'Electric', 'RL', 'Supporter', 'Best Seller', 2),
(13, 3, 'Aria', 'Tetra', 'Water', 'MG', 'Attacker', 'Prima Donna', 2),
(14, 3, 'Asuka', 'Abnormal', 'Fire', 'AR', 'Attacker', 'NERV', 3),
(15, 3, 'Asuka: WILLE', 'Abnormal', 'Wind', 'MG', 'Attacker', 'WILLE', 3),
(16, 3, 'Bay', 'Tetra', 'Fire', 'RL', 'Defender', 'Rewind', 2),
(17, 3, 'Biscuit', 'Tetra', 'Electric', 'RL', 'Supporter', 'Happy Zoo', 2),
(18, 3, 'Blanc', 'Tetra', 'Wind', 'AR', 'Defender', '777', 2),
(19, 3, 'Bready', 'Tetra', 'Water', 'SR', 'Attacker', 'Cooking Oil', 3),
(20, 3, 'Brid', 'Elysion', 'Water', 'AR', 'Attacker', 'Infinity Rail', 3),
(21, 3, 'Brid: Silent Track', 'Elysion', 'Fire', 'SG', 'Supporter', 'Infinity Rail', 2),
(22, 3, 'Centi', 'Missilis', 'Iron', 'RL', 'Defender', 'Mighty Tools', 2),
(23, 3, 'Chime', 'Pilgrim', 'Iron', 'SMG', 'Supporter', 'White Knight', 2),
(24, 3, 'Cinderella', 'Pilgrim', 'Electric', 'RL', 'Defender', 'Old Tales', 3),
(25, 3, 'Clay', 'Tetra', 'Electric', 'SMG', 'Supporter', 'Rewind', 2),
(26, 3, 'Cocoa', 'Tetra', 'Fire', 'SR', 'Supporter', 'Maid For You', 1),
(27, 3, 'Crow', 'Missilis', 'Fire', 'SMG', 'Defender', 'Exotic', 3),
(28, 3, 'Crown', 'Pilgrim', 'Iron', 'MG', 'Defender', 'White Knight', 2),
(29, 3, 'Crust', 'Tetra', 'Water', 'RL', 'Supporter', 'Cooking Oil', 2),
(30, 3, 'D', 'Elysion', 'Wind', 'SMG', 'Attacker', 'Perilous Siege', 3),
(31, 3, 'D: Killer Wife', 'Elysion', 'Fire', 'SR', 'Supporter', 'Perilous Siege', 1),
(32, 3, 'Delta: Ninja Thief', 'Elysion', 'Water', 'MG', 'Defender', 'The Scouts', 2),
(33, 3, 'Diesel', 'Elysion', 'Wind', 'MG', 'Defender', 'Infinity Rail', 2),
(34, 3, 'Diesel: Winter Sweets', 'Elysion', 'Fire', 'RL', 'Attacker', 'Infinity Rail', 3),
(35, 3, 'Dolla', 'Tetra', 'Wind', 'SR', 'Supporter', 'Talentum', 2),
(36, 3, 'Dorothy', 'Pilgrim', 'Water', 'AR', 'Supporter', 'Inherit', 1),
(37, 3, 'Dorothy: Serendipity', 'Pilgrim', 'Water', 'SG', 'Attacker', 'Inherit', 3),
(38, 3, 'Drake', 'Missilis', 'Fire', 'SG', 'Attacker', 'Matis', 3),
(39, 3, 'Eve', 'Abnormal', 'Iron', 'AR', 'Attacker', '7th Airborne Squad', 3),
(40, 3, 'Ein', 'Missilis', 'Electric', 'SR', 'Attacker', 'School Circle', 3),
(41, 3, 'Elegg', 'Missilis', 'Electric', 'MG', 'Supporter', 'Electric Shock', 2),
(42, 3, 'Elegg: Boom and Shock', 'Missilis', 'Water', 'MG', 'Attacker', 'Electric Shock', 3),
(43, 3, 'Emilia', 'Abnormal', 'Water', 'RL', 'Attacker', 'Emilia''s Faction', 3),
(44, 3, 'Emma', 'Elysion', 'Fire', 'MG', 'Supporter', 'Absolute', 1),
(45, 3, 'Emma: Tactical Upgrade', 'Elysion', 'Fire', 'MG', 'Supporter', 'Absolute', 1),
(46, 3, 'Epinel', 'Missilis', 'Wind', 'SMG', 'Attacker', 'Nepenthe', 3),
(47, 3, 'Eunhwa', 'Elysion', 'Fire', 'SR', 'Attacker', 'Absolute', 2),
(48, 3, 'Eunhwa: Tactical Upgrade', 'Elysion', 'Fire', 'SR', 'Attacker', 'Absolute', 2),
(49, 3, 'Exia', 'Tetra', 'Electric', 'SR', 'Supporter', 'Protocol', 1),
(50, 3, 'Flora', 'Missilis', 'Electric', 'MG', 'Supporter', 'Botanic Garden', 2),
(51, 3, 'Folkwang', 'Tetra', 'Water', 'AR', 'Defender', 'Nepenthe', 2),
(52, 3, 'Frima', 'Tetra', 'Iron', 'SR', 'Supporter', 'Cafe Sweety', 1),
(53, 3, 'Grave', 'Pilgrim', 'Fire', 'AR', 'Supporter', 'Old Tales', 2),
(54, 3, 'Guillotine', 'Elysion', 'Electric', 'MG', 'Attacker', 'Extrinsic', 3),
(55, 3, 'Guillotine: Winter Slayer', 'Elysion', 'Water', 'AR', 'Attacker', 'Extrinsic', 3),
(56, 3, 'Guilty', 'Missilis', 'Wind', 'SG', 'Attacker', 'Real Kindness', 2),
(57, 3, 'Harran', 'Pilgrim', 'Electric', 'SR', 'Attacker', 'Inherit', 3),
(58, 3, 'Helm', 'Elysion', 'Water', 'SR', 'Attacker', 'Aegis', 3),
(59, 3, 'Helm: Aquamarine', 'Elysion', 'Iron', 'AR', 'Attacker', 'Aegis', 2),
(60, 3, 'Isabel', 'Pilgrim', 'Electric', 'SG', 'Attacker', 'Inherit', 3),
(61, 3, 'Jackal', 'Missilis', 'Iron', 'RL', 'Defender', 'Exotic', 1),
(62, 3, 'Jill', 'Abnormal', 'Electric', 'AR', 'Attacker', 'B.S.T', 3),
(63, 3, 'Julia', 'Missilis', 'Iron', 'AR', 'Attacker', 'Master Hand', 3),
(64, 3, 'K', 'Elysion', 'Electric', 'SMG', 'Attacker', 'Perilous Siege', 3),
(65, 3, 'Kilo', 'Missilis', 'Fire', 'MG', 'Defender', 'Heavy Gram', 3),
(66, 3, 'Label', 'Elysion', 'Iron', 'AR', 'Defender', 'Best Seller', 1),
(67, 3, 'Laplace', 'Missilis', 'Iron', 'RL', 'Attacker', 'Matis', 3),
(68, 3, 'Leona', 'Tetra', 'Water', 'SG', 'Supporter', 'Happy Zoo', 2),
(69, 3, 'Liberalio', 'Pilgrim', 'Wind', 'SR', 'Attacker', 'Heretic', 3),
(70, 3, 'Liter', 'Missilis', 'Iron', 'SMG', 'Supporter', 'Mighty Tools', 1),
(71, 3, 'Little Mermaid', 'Pilgrim', 'Wind', 'SMG', 'Supporter', 'Old Tales', 1),
(72, 3, 'Ludmilla', 'Tetra', 'Water', 'SMG', 'Defender', 'Unlimited', 1),
(73, 3, 'Ludmilla: Winter Owner', 'Tetra', 'Water', 'MG', 'Attacker', 'Unlimited', 3),
(74, 3, 'Maiden', 'Elysion', 'Electric', 'SG', 'Attacker', 'Extrinsic', 3),
(75, 3, 'Maiden: Ice Rose', 'Elysion', 'Electric', 'RL', 'Defender', 'Extrinsic', 3),
(76, 3, 'Makima', 'Abnormal', 'Water', 'SMG', 'Defender', 'Devil Hunter', 2),
(77, 3, 'Mana', 'Missilis', 'Wind', 'AR', 'Attacker', 'M.M.R', 3),
(78, 3, 'Marciana', 'Elysion', 'Iron', 'SG', 'Supporter', 'Academia', 2),
(79, 3, 'Mari', 'Abnormal', 'Electric', 'SR', 'Supporter', 'NERV', 2),
(80, 3, 'Mary', 'Tetra', 'Water', 'SG', 'Supporter', 'Seraphim', 1),
(81, 3, 'Mary: Bay Goddess', 'Tetra', 'Water', 'SR', 'Supporter', 'Seraphim', 1),
(82, 3, 'Mast', 'Elysion', 'Electric', 'SMG', 'Supporter', 'Aegis', 2),
(83, 3, 'Mast: Romantic Maid', 'Elysion', 'Water', 'MG', 'Supporter', 'Aegis', 2),
(84, 3, 'Maxwell', 'Missilis', 'Iron', 'SR', 'Attacker', 'Matis', 3),
(85, 3, 'Mica: Snow Buddy', 'Tetra', 'Iron', 'SMG', 'Supporter', 'The Carronades', 1),
(86, 3, 'Mihara: Bonding Chain', 'Missilis', 'Fire', 'MG', 'Attacker', 'Wardress', 3),
(87, 3, 'Milk', 'Tetra', 'Water', 'SR', 'Attacker', 'Cafe Sweety', 1),
(88, 3, 'Milk: Blooming Bunny', 'Tetra', 'Iron', 'SR', 'Attacker', 'Cafe Sweety', 3),
(89, 3, 'Miranda', 'Elysion', 'Fire', 'SMG', 'Supporter', 'A.C.P.U', 1),
(90, 3, 'Modernia', 'Pilgrim', 'Fire', 'MG', 'Attacker', 'Heretic', 3),
(91, 3, 'Moran', 'Tetra', 'Electric', 'AR', 'Defender', 'Underworld Queen', 1),
(92, 3, 'Mori', 'Missilis', 'Wind', 'AR', 'Defender', 'Incubator', 2),
(93, 3, 'Naga', 'Missilis', 'Electric', 'SG', 'Supporter', 'Dazzling Pearl', 2),
(94, 3, 'Nayuta', 'Pilgrim', 'Wind', 'SMG', 'Supporter', 'Pioneer', 2),
(95, 3, 'Neon: Blue Ocean', 'Elysion', 'Water', 'MG', 'Attacker', 'Counters', 3),
(96, 3, 'Nero', 'Tetra', 'Fire', 'SMG', 'Defender', 'Happy Zoo', 2),
(97, 3, 'Nihilister', 'Pilgrim', 'Fire', 'SR', 'Attacker', 'Heretic', 2),
(98, 3, 'Noah', 'Pilgrim', 'Wind', 'RL', 'Defender', 'Inherit', 2),
(99, 3, 'Noir', 'Tetra', 'Wind', 'SG', 'Attacker', '777', 3),
(100, 3, 'Noise', 'Tetra', 'Electric', 'RL', 'Supporter', 'Prima Donna', 1),
(101, 3, 'Novel', 'Tetra', 'Iron', 'SMG', 'Defender', 'Protocol', 2),
(102, 3, 'Pepper', 'Missilis', 'Wind', 'SG', 'Supporter', 'Seraphim', 1),
(103, 3, 'Phantom', 'Elysion', 'Water', 'AR', 'Attacker', 'Best Seller', 3),
(104, 3, 'Poli', 'Elysion', 'Water', 'SG', 'Defender', 'A.C.P.U', 2),
(105, 3, 'Power', 'Abnormal', 'Fire', 'RL', 'Attacker', 'Devil Hunter', 3),
(106, 3, 'Privaty', 'Elysion', 'Water', 'AR', 'Attacker', 'Triangle', 3),
(107, 3, 'Privaty: Unkind Maid', 'Elysion', 'Electric', 'SG', 'Attacker', 'Maid For You', 3),
(108, 3, 'Quency', 'Missilis', 'Electric', 'SMG', 'Supporter', 'Real Kindness', 2),
(109, 3, 'Quency: Escape Queen', 'Missilis', 'Water', 'SMG', 'Attacker', 'Real Kindness', 3),
(110, 3, 'Quiry', 'Elysion', 'Wind', 'RL', 'Supporter', 'A.C.P.U', 3),
(111, 3, 'Rapi: Red Hood', 'Elysion', 'Fire', 'MG', 'Attacker', 'Counters', 3),
(112, 3, 'Rapunzel', 'Pilgrim', 'Iron', 'RL', 'Supporter', 'Pioneer', 1),
(113, 3, 'Rapunzel: Pure Grace', 'Pilgrim', 'Iron', 'SR', 'Defender', 'Goddess', 1),
(114, 3, 'Raven', 'Abnormal', 'Iron', 'RL', 'Attacker', '2nd Airborne Squad', 3),
(115, 3, 'Red Hood', 'Pilgrim', 'Iron', 'SR', 'Attacker', 'Goddess', 4),
(116, 3, 'Rei', 'Tetra', 'Water', 'SMG', 'Defender', 'School Circle', 1),
(117, 3, 'Rei Ayanami', 'Abnormal', 'Fire', 'MG', 'Attacker', 'NERV', 3),
(118, 3, 'Rei Ayanami (Tentative Name),', 'Abnormal', 'Wind', 'AR', 'Attacker', 'NERV', 3),
(119, 3, 'Rem', 'Abnormal', 'Water', 'MG', 'Supporter', 'Emilia''s Faction', 2),
(120, 3, 'Rosanna', 'Tetra', 'Electric', 'MG', 'Attacker', 'Underworld Queen', 1),
(121, 3, 'Rosanna: Chic Ocean', 'Tetra', 'Wind', 'AR', 'Supporter', 'Underworld Queen', 2),
(122, 3, 'Rouge', 'Tetra', 'Electric', 'SR', 'Supporter', '777', 1),
(123, 3, 'Rumani', 'Tetra', 'Fire', 'RL', 'Defender', 'Nepenthe', 1),
(124, 3, 'Rupee', 'Tetra', 'Iron', 'AR', 'Attacker', 'Talentum', 2),
(125, 3, 'Rupee: Winter Shopper', 'Tetra', 'Electric', 'AR', 'Defender', 'Talentum', 1),
(126, 3, 'Sakura', 'Tetra', 'Fire', 'SR', 'Supporter', 'Underworld Queen', 1),
(127, 3, 'Sakura: Bloom in Summer', 'Tetra', 'Wind', 'AR', 'Attacker', 'Underworld Queen', 3),
(128, 3, 'Scarlet', 'Pilgrim', 'Electric', 'AR', 'Attacker', 'Pioneer', 3),
(129, 3, 'Scarlet: Black Shadow', 'Pilgrim', 'Wind', 'RL', 'Attacker', 'Goddess', 3),
(130, 3, 'Signal', 'Elysion', 'Fire', 'SMG', 'Attacker', 'The Scouts', 2),
(131, 3, 'Sin', 'Missilis', 'Electric', 'AR', 'Defender', 'Real Kindness', 2),
(132, 3, 'Snow White', 'Pilgrim', 'Iron', 'AR', 'Attacker', 'Pioneer', 3),
(133, 3, 'Snow White: Heavy Arms', 'Pilgrim', 'Water', 'SR', 'Attacker', 'Goddess', 3),
(134, 3, 'Snow White: Innocent Days', 'Pilgrim', 'Iron', 'AR', 'Attacker', 'Goddess', 3),
(135, 3, 'Soda', 'Tetra', 'Fire', 'MG', 'Supporter', 'Maid For You', 1),
(136, 3, 'Soda: Twinkling Bunny', 'Tetra', 'Iron', 'SG', 'Attacker', 'Maid For You', 3),
(137, 3, 'Soline', 'Elysion', 'Iron', 'SMG', 'Attacker', 'Infinity Rail', 3),
(138, 3, 'Soline: Frost Ticket', 'Elysion', 'Water', 'SG', 'Supporter', 'Infinity Rail', 1),
(139, 3, 'Sora', 'Elysion', 'Wind', 'RL', 'Supporter', 'Over The Horizon', 1),
(140, 3, 'Sugar', 'Tetra', 'Iron', 'SG', 'Attacker', 'Cafe Sweety', 3),
(141, 3, 'Tia', 'Missilis', 'Iron', 'RL', 'Defender', 'Dazzling Pearl', 1),
(142, 3, 'Tove', 'Missilis', 'Water', 'AR', 'Supporter', 'Unlimited', 1),
(143, 3, 'Trina', 'Missilis', 'Electric', 'RL', 'Supporter', 'Botanic Garden', 2),
(144, 3, 'Trony', 'Missilis', 'Fire', 'SR', 'Attacker', 'Electric Shock', 3),
(145, 3, 'Velvet', 'Tetra', 'Wind', 'SR', 'Supporter', 'Maid For You', 2),
(146, 3, 'Vesti', 'Elysion', 'Water', 'RL', 'Attacker', 'Absolute', 3),
(147, 3, 'Vesti: Tactical Upgrade', 'Elysion', 'Fire', 'RL', 'Attacker', 'Absolute', 3),
(148, 3, 'Viper', 'Tetra', 'Water', 'SG', 'Attacker', 'Exotic', 2),
(149, 3, 'Volume', 'Tetra', 'Wind', 'SMG', 'Attacker', 'Prima Donna', 1),
(150, 3, 'Yan', 'Tetra', 'Fire', 'RL', 'Supporter', 'Talentum', 1),
(151, 3, 'Yulha', 'Tetra', 'Fire', 'SR', 'Attacker', 'Triangle', 3),
(152, 3, 'Yuni', 'Missilis', 'Fire', 'RL', 'Defender', 'Wardress', 2),
(153, 3, 'Zwei', 'Elysion', 'Electric', 'SG', 'Supporter', 'School Circle', 1),
(154, 2, 'Anchor', 'Elysion', 'Wind', 'RL', 'Defender', 'Aegis', 1),
(155, 2, 'Anis', 'Tetra', 'Iron', 'RL', 'Defender', 'Counters', 2),
(156, 2, 'Belorta', 'Tetra', 'Electric', 'RL', 'Attacker', 'The Carronades', 2),
(157, 2, 'Claire', 'Abnormal', 'Electric', 'RL', 'Supporter', 'B.S.T', 1),
(158, 2, 'Delta', 'Elysion', 'Wind', 'SR', 'Defender', 'The Scouts', 2),
(159, 2, 'Ether', 'Missilis', 'Electric', 'SG', 'Defender', 'M.M.R', 1),
(160, 2, 'Himeno', 'Abnormal', 'Wind', 'SR', 'Supporter', 'Devil Hunter', 2),
(161, 2, 'Lily', 'Abnormal', 'Wind', 'SMG', 'Supporter', '5th Airborne Squad', 2),
(162, 2, 'Mica', 'Tetra', 'Wind', 'RL', 'Supporter', 'The Carronades', 1),
(163, 2, 'Mihara', 'Missilis', 'Water', 'AR', 'Attacker', 'Wardress', 3),
(164, 2, 'Misato', 'Abnormal', 'Iron', 'SMG', 'Supporter', 'NERV', 1),
(165, 2, 'N102', 'Missilis', 'Water', 'RL', 'Supporter', 'Recall & Release', 1),
(166, 2, 'Neon', 'Elysion', 'Fire', 'SG', 'Supporter', 'Counters', 1),
(167, 2, 'Neve', 'Tetra', 'Water', 'SG', 'Attacker', 'Unlimited', 3),
(168, 2, 'Pascal', 'Abnormal', 'Iron', 'RL', 'Supporter', 'Machine Lifeform', 1),
(169, 2, 'Ram', 'Abnormal', 'Wind', 'SR', 'Defender', 'Emilia''s Faction', 1),
(170, 2, 'Rapi', 'Elysion', 'Fire', 'AR', 'Attacker', 'Counters', 3),
(171, 2, 'Sakura Suzuhara', 'Abnormal', 'Water', 'SMG', 'Supporter', 'WILLE', 1),
(172, 1, 'Product 08', 'Missilis', 'Electric', 'SR', 'Supporter', 'Replace', 1),
(173, 1, 'Product 12', 'Missilis', 'Fire', 'MG', 'Attacker', 'Replace', 3),
(174, 1, 'Product 23', 'Missilis', 'Wind', 'SG', 'Supporter', 'Replace', 2),
(175, 1, 'Soldier EG', 'Elysion', 'Electric', 'AR', 'Attacker', 'Replace', 3),
(176, 1, 'Soldier FA', 'Elysion', 'Iron', 'SG', 'Defender', 'Replace', 2),
(177, 1, 'Soldier OW', 'Elysion', 'Fire', 'SMG', 'Supporter', 'Replace', 1),
(178, 1, 'iDoll Flower', 'Tetra', 'Wind', 'RL', 'Defender', 'Replace', 1),
(179, 1, 'iDoll Ocean', 'Tetra', 'Water', 'SMG', 'Supporter', 'Replace', 1),
(180, 1, 'iDoll Sun', 'Tetra', 'Iron', 'AR', 'Supporter', 'Replace', 3);